version: '3.8'

services:
  dev:
    build:
      context: .
      target: development
      args:
        PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Optional: enables live reload in dev
    environment:
      - FLASK_ENV=development

  prod:
    build:
      context: .
      target: production
      args:
        PORT: 5000
    ports:
      - "5000:5000"